### ISSUE TITLE
Fixing ZZT/Super ZZT file detection (contributing file format support)

### ISSUE THREAD

**Issue by asiekierka** [Sembiance/dexvert#1]
The repository lists ZZT and Super ZZT files as UNSUPPORTED, yet Discmaster is clearly detecting them - with about 80% false positives, unfortunately - and I can't possibly figure out how it is currently doing it from the codebase as-is, nor do I seem to be able get it to work enough to try locally on a set of sample files.

As a person [familiar with the inner workings of ZZT](https://github.com/asiekierka/reconstruction-of-zzt), I'd like to contribute a more resilient detector, as I am very much interested in preserving and documenting every ZZT/Super ZZT/MegaZeux game world out there.

**Comment by asiekierka** [comment]
Magic bytes won't do, as "0xFFFF at offset 0" is literally the only actual "magic byte" in the format; the others are incidental. Let me explain:

```
0xFFFF at offset 0 // version number; this is 0xFFFF (-1) for ZZT, and 0xFFFE (-2) for Super ZZT. This is actually optional in the engine's world loading routine, but all known saved worlds use it.
0x00 at offset 3 // high byte of board count; as ZZT has a limit of 100 boards (+ title screen) and Super ZZT of 32 boards (+ title screen), it will always be 0, incidentally.
0x0000000000000000 at offset 7 // v
0x00000000000000 at offset 18 // default values in the "world info" structure; these are NOT guaranteed in any way to be zeroes, especially for save files.
```

Extensions are generally either `.ZZT` (ZZT world), `.SZT` (Super ZZT world), or `.SAV` (ZZT or Super ZZT save file); the engine will not accept any other extensions by default, albeit a few worlds used different extensions together with a batch file to ensure, for example, loading a custom Font Mania character set before.

I'd say that, for now, "extension" + "at least 512 bytes (1024 for .SZT)" (there's a header padding system of exactly this size, so a valid world will never be smaller) + "magic bytes 0, 1, and 3" should be sufficient as a quick patch.

The Museum of ZZT [has a JavaScript-based system](https://museumofzzt.com/file/view/zzt/?file=TOWN.ZZT) for browsing ZZT/Super ZZT world data, but I'm not sure if you want to integrate that. I could also develop a custom command-line tool to check world validity and/or generate PNG screenshots as you requested.

**Comment by asiekierka** [comment]
I'm moving MegaZeux to a separate issue.

**Comment by Sembiance** [comment]
> The Museum of ZZT [has a JavaScript-based system](https://museumofzzt.com/file/view/zzt/?file=TOWN.ZZT) for browsing ZZT/Super ZZT world data, but I'm not sure if you want to integrate that.

I took a peek at the [code for it](https://github.com/DrDos0016/museum-of-zzt/blob/6c6fd11a02d1ab594c1e9104f96de9b3c4946a08/museum_site/static/js/file_viewer.js) and it's not something I'd want to try and integrate. I think the best approach would be to generate png screenshots of each board.

> I could also develop a custom command-line tool to check world validity and/or generate PNG screenshots as you requested.

If you were to do this (or point me to an existing one that runs on linux, MS-DOS, or win2k/winxp) then I'd integrate it into dexvert so that any detected ZZT/Super ZZT files would generate X PNG files, 1 for each board. Thus when discmaster picks it up, you'll be able to see previews of each board. Bonus points of the tool could name each PNG with the board title name.

**Comment by asiekierka** [comment]
An existing one that runs on Linux is available [here](https://github.com/asiekierka/zzt-toolbox/blob/master/screenshot_grab.py), using Python 3, Pillow and the Zookeeper library (same as most of the Museum of ZZT's tooling) available [here](https://github.com/DrDos0016/zookeeper). If you prefer something that's more self-contained, I could write one using Go or modern Java instead - we have world-parsing libraries for both.

**Comment by Sembiance** [comment]
Thanks for the Zookeeper link and screenshotter link! dexvert now supports rendering PNG screenshots of boards within ZZT files!
DiscMaster only has re-processed one item so far: http://discmaster.textfiles.com/browse/8255/odm60.zip/ZCITY.ZZT

Over the next several days, DiscMaster will be re-processing all the CDs with ZZT files on them and removing the false positives as well.

Do you know of a similar tool to Zookeeper but for SuperZZT?

**Comment by Sembiance** [comment]
Both ZZT and Super ZZT files are properly detected now, was completed back in Nov I believe.
