### ISSUE TITLE
Point vintage URLs to Wayback Machine?

### ISSUE THREAD

**Issue by gingerbeardman** [Sembiance/dexvert#10]
Almost all old links have rotted away. 

How about automatically reformatting each URL in HTML files to point to Wayback Machine, with the timestamp of the file containing the link?

Example page containing dead links: 
- http://discmaster.textfiles.com/view/11593/db.tidbits.com.tar/db.tidbits.com/issue/406.html

😎

**Comment by gingerbeardman** [comment]
More thought shows timestamp might be tricky:

Example link from the above HTML page:
- http://www.bekkoame.or.jp/~thoru/

"newest" wayback snapshot (here results in 404 page)
- https://web.archive.org/web/2/http://www.bekkoame.or.jp/~thoru/

"another" wayback snapshot (here from 1998)
- https://web.archive.org/web/1/http://www.bekkoame.or.jp/~thoru/
- not sure what "1" signifies in terms of wayback snapshot

"oldest" wayback snapshot (here from 1996)
- https://web.archive.org/web/0/http://www.bekkoame.or.jp/~thoru/

"all" wayback snapshots (a bit user unfriendly)
- https://web.archive.org/web/*/http://bekkoame.or.jp/~thoru/

**Comment by Sembiance** [comment]
I put code live yesterday that handles this. It points to a wayback link with a specific date. The date I use is the date of the HTML file the link is in (which is set from the archive or ISO it was contained within). The wayback machine then seems to pick the closest copy it has to that date (not sure if it goes newer and older or just older, but seems to work). So the links end up pointing to period appropriate version of the webpages.

I've done initial testing on a handful of small items and Discmaster is currently reprocessing the item you linked. I was waiting to see how that went before commenting :)

**Comment by Sembiance** [comment]
By the way, I am using the link like: https://web.archive.org/web/20070205111659/macblog.com
I replace 2007... with YYYYMMDD000000

**Comment by gingerbeardman** [comment]
Ace! I'll watch out for it.

**Comment by Sembiance** [comment]
This is complete now. Discmaster has reprocessed the item you originally mentioned and the external links all now go to the Wayback version at the appropriate date/time. Tested a bunch of different links, seems to work. Wayback machine is a little slow, but it does load up.

**Comment by gingerbeardman** [comment]
Cool! Thanks.

At (same as OP)
- http://discmaster.textfiles.com/view/11593/db.tidbits.com.tar/db.tidbits.com/issue/406.html

I noticed that the http://www.softmaterial.com link points to
- http://discmaster.textfiles.com/file/11593/db.tidbits.com.tar/db.tidbits.com/index.html

whereas in the source it 
- http://discmaster.textfiles.com/view/11593/db.tidbits.com.tar/db.tidbits.com/issue/406.orig

it is

```
<<A HREF="http://www.softmaterial.com/">http://www.softmaterial.com/</A>><BR>
```

so it should point to an external site, right?

**Comment by Sembiance** [comment]
Whoops!

**Comment by Sembiance** [comment]
I figured out the problem here and have updated the code and Discmaster is reprocessing this item. Once it's complete I'll update here.

**Comment by Sembiance** [comment]
Ok, it's been reprocessed and after clearing my cache and poking around, it looks good to me now.

Whenever you happen to get the chance to poke around, let me know if you see anything wrong. Thanks :)

**Comment by gingerbeardman** [comment]
Looks good to me, cheers
