### ISSUE TITLE
Additional file extension request

### ISSUE THREAD

**Issue by gingerbeardman** [Sembiance/dexvert#13]
HTML
- .hts

(Not checked: HTM, HTML, HTX, XHTML, SHTML, PHTML)

Never heard of this myself but there we go!

Examples
- http://discmaster.textfiles.com/view/10383/NIKKEI-MAC-CD-VOL-17-1998-09.ISO.7z/NIKKEI-MAC-CD-VOL-17-1998-09.ISO/NIKKEIMAC.COM/hotnews/9807/typedesigner.hts
- http://discmaster.textfiles.com/view/847/Hidden%20Truth.iso/data/genufo2/ufoinfo/museums.hts
- etc

**Comment by gingerbeardman** [comment]
> Discmaster will reprocess the 34 CDs that contained the 5,000 or so .hts HTML files.

Love it! Partial updates - nice.

**Comment by Sembiance** [comment]
The reprocessing finished and the files processed properly. Thanks again for submitting the issue!!
