### ISSUE TITLE
Search by language?

### ISSUE THREAD

**Issue by gingerbeardman** [Sembiance/dexvert#14]
I can't remember how you flag Japanese media like mine, but it would be useful to be able to limit the search similarly.

**Comment by Sembiance** [comment]
It's a manual flag that is set by hand on each item when it's first registered into the system and metadata is set. It's a bit 'hacky' as it's kinda a combo of 3 things platform/language/encodnig.  Surfacing it in the search interface may cause some confusion based on how it's currently hacked it into the system. I'll need to give it some thought about how best I might be able to clean it up before exposing it.

**Comment by gingerbeardman** [comment]
Don't worry about it.

Searching that way would also miss and random chance of finding stuff on discs from elsewhere.

Happy for you to close
