### ISSUE TITLE
Easier way to view all images in directory?

### ISSUE THREAD

**Issue by gingerbeardman** [Sembiance/dexvert#15]
Example

- http://discmaster.textfiles.com/browse/15974/Precos%204.97%20Computer%202000.iso/pc/info/3periphe/epson/printlib/library/shared.dir

This came on in my RSS for Thoru Yamamoto. A real nice find, totally unknown!

I wanted to view all three images full size one after the other. 

> Turns out these images are small anyway so it was a dead end. 

But, currently, viewing multiple images in sequence is difficult as the prev/next buttons are small and separate than the images. 

I'm wondering if there's a better way. Some kind of "light box", slideshow, coverflow, or other interface.

**Comment by Sembiance** [comment]
If you are on a computer, you can press the left and right arrows on the keyboard to go to prev/next image. I tend to use this a lot.

As for improving the UI for easier prev/next image viewing, yah, there are betters ways, but I'll need to think about that some more, especially how it may impact the usability of the site on vintage browsers/computers.

**Comment by gingerbeardman** [comment]
Ah, I am mostly on iOS (which has other challenges).

How about hooking swipes on the screen to do the same as cursor keys?

**Comment by Sembiance** [comment]
The DiscMaster project is changing hands and I am no longer associated with it. I will be mantaining the dexvert project (the conversion part) including releasing a 1.0 beta release soon, but issues related directly to the DiscMaster website are no longer something I have control over and thus are out of my purview.
