### ISSUE TITLE
News page numbering

### ISSUE THREAD

**Issue by gingerbeardman** [Sembiance/dexvert#17]
I just sent somebody this link: http://discmaster.textfiles.com/news12.html

But it occurred to me... will the contents of this page change over time? Seems to me it will.

So I wondered if they older news pages could be named in such a way that their content will not change? Maybe they could be split by month/week/day?

**Comment by Sembiance** [comment]
Done.

You can now access any day of news with this syntax: http://discmaster.textfiles.com/news/2023-01-31.html

The first news page now shows 5 days and every subsequent 'older' link now goes to the specific day in question. Even though the main index page shows 5 days on 1 page, each of those individual days are also available to link directly to.

I'm afraid the previous link you sent to someone is now 404. You'll need to find the specific news day in question and link to that.

Feel free to re-open if this solution isn't sufficient :)

**Comment by Sembiance** [comment]
Just updated it again, the individual date headers are hyperlinks to the day in question. So if you need to send a link to a day from the main news.html page, it's easier, just copy link.

**Comment by gingerbeardman** [comment]
Sweet, thanks!

**Comment by gingerbeardman** [comment]
The only other request would be to get two links at the bottom for older/newer to be able to travel through time.

Also, just wanted to say how refreshing it is to have my feature requests heard and in most cases implemented — continued thanks.

**Comment by gingerbeardman** [comment]
Thanks!

Just noticed it was added as I was going through looking for SGI discs.

✨

**Comment by Sembiance** [comment]
News pages now have Newer/Older links. Also the top level news header now links to news.html :)
