### ISSUE TITLE
Ability to search list of CD-ROMs by title

### ISSUE THREAD

**Issue by gingerbeardman** [Sembiance/dexvert#18]
Either using the search interface, or not.

I'm looking for IRIX/SGI CDs

**Comment by Sembiance** [comment]
A workaround you can use in the meantime, if you go to the 'All Genres' page: http://discmaster.textfiles.com/cd-rom/All%20Genres.html

You can Control-F in your browser for SGI or IRIX, etc

I'll think about how best to implement a more official/easier to use search.

**Comment by gingerbeardman** [comment]
Thanks for the workaround.

**Comment by Sembiance** [comment]
The DiscMaster project is changing hands and I am no longer associated with it. I will be mantaining the dexvert project (the conversion part) including releasing a 1.0 beta release soon, but issues related directly to the DiscMaster website are no longer something I have control over and thus are out of my purview.

**Comment by gingerbeardman** [comment]
No worries, thanks for all your hard work. It's an amazing thing and thank you for making it. Hopefully it will live on as well as we can hope! And congrats if congrats are in order. 🎉

**Comment by Sembiance** [comment]
discmaster2 has a 'search' box on category pages, so easier to find a particular CD
