### ISSUE TITLE
Colour of local/external HTML links?

### ISSUE THREAD

**Issue by gingerbeardman** [Sembiance/dexvert#19]
I sent a DiscMaster link to somebody and they commented "this is just the same snapshot as Wayback Machine has"

It wasn't, but the reformatted Wayback links made them think it was. 

So I wondered if it will be possible to differentiate local DiscMaster links and Wayback links?

The obvious way would be different colour for local/external links. But it's not so accessible. And maybe it would need a description on the page of the differences. 

Maybe colour and an icon? but that would break the layout of some pages. 

I'll leave the difficult decision up to you 😅

**Comment by Sembiance** [comment]
Hrm. I'll have to think about this some more. I understand the reasoning you laid out, but I'm not sure I'm in love with changing the visual appearance of the pages with icons near the links. Different coloured links would be a less impactful change but I'd have to choose a color carefully and also consider the :visited state as well. Also would have to think about whether this is done as a CSS insert into every page or a style attribute addition to every link. I'll have to think on it some more.

**Comment by gingerbeardman** [comment]
I was thinking Blue local links.

And Red for external links.

Purple could be visited for both?

**Comment by Sembiance** [comment]
The DiscMaster project is changing hands and I am no longer associated with it. I will be mantaining the dexvert project (the conversion part) including releasing a 1.0 beta release soon, but issues related directly to the DiscMaster website are no longer something I have control over and thus are out of my purview.
