### ISSUE TITLE
MegaZeux file detection

### ISSUE THREAD

**Issue by asiekierka** [Sembiance/dexvert#2]
### Detecting MegaZeux worlds with magic bytes

The MegaZeux world file header (for all versions) is documented [here](https://www.digitalmzx.com/fileform.html#world). From there, we can see that the following logic is sufficient:

* The file extension is always `MZX` (world file),
* If byte 25 is zero, the bytes 26-28 (magic) are either `MZX`, `MZ2`, `MZA`, or `M\x02?`, where ? is any byte;
* If byte 25 is non-zero, the bytes 41-43 (magic) are either `MZX`, `MZ2`, `MZA`, or `M\x02?`, where ? is any byte;

Bytes 0-24 can then be used to parse the world title (codepage 437, null-terminated).

### Detecting MegaZeux boards with magic bytes

Like the instructions above:

* The file extension is always `MZB` (board file),
* Byte 0 is always 0xFF,
* Bytes 1-3 (magic) are either `MB2` or `M\x02?`, where ? is any byte;

Bytes 0-24 can then be used to parse the world title.

### Detecting MegaZeux save files with magic bytes

Like the instructions above:

* The file extension is always `SAV`,
* The bytes 0-4 (magic) are either `MZSV2`, `MZXSA`, or `MZS\x02?`, where ? is any byte.

### Detecting MegaZeux 2.00+ worlds with checkres

The most comprehensive to detect a MegaZeux 2.00+ file is to use `checkres`, a tool built as part of the MegaZeux distribution ([source code](https://github.com/AliceLR/megazeux), directory src/utils):

`./checkres -AV [file]`

If the error code is 1, the file is not a valid MegaZeux 2.00+ file. If the error code is 0, the file is a valid MegaZeux 2.00+ file - additionally, a CSV will be output containing the file's dependencies and whether or not they have been located, for example:

```
Required by,Expected file,Status,Found in
CAVERNS.MZX,CV_BALON.MOD,FOUND,.
CAVERNS.MZX,CV_BOSS.MOD,FOUND,.
CAVERNS.MZX,CV_HEVEN.MOD,FOUND,.
CAVERNS.MZX,CV_MAGIC.MOD,FOUND,.
CAVERNS.MZX,CV_STORY.MOD,FOUND,.
CAVERNS.MZX,CV_TECH.MOD,FOUND,.
CAVERNS.MZX,CV_TITLE.MOD,FOUND,.
```

Notice that I mentioned "2.00+" (this is also important, as for very modern files - we're talking the last few years - the format changed significantly, being effectively a ZIP file with a special file layout). For MegaZeux 1.xx worlds (the only MegaZeux worlds currently on DiscMaster), the output will be as follows:

```
ERROR: Worlds from MegaZeux 1.xx are not supported by this utility.
```

As with ZZT/Super ZZT, I am open to working on a dedicated tool to handle these (though PNG screenshot exports would be a little trickier).

**Comment by Sembiance** [comment]
Thanks for the info. I'm pretty swamped with 'another project' at the moment, but will get to this as soon as I'm able, though it may be a few weeks.

**Comment by asiekierka** [comment]
You might be able to use https://github.com/kristomu/spider-of-zzt , which is a tool developed by @kristomu for detecting "interesting" ZZT/Super ZZT/MegaZeux files in spider activities. Though I don't exactly have docs for it :-(

**Comment by kristomu** [comment]
It's for detecting interesting files in general, "interesting" being ZZT and MegaZeux world/board/save files and text files that refer to the games (e.g. web pages about ZZT).

For the former, the useful functions are zzt_szt_check (checks for ZZT and SuperZZT world and save files), is_brd (checks for ZZT board files), and get_mzx_type (checks for MegaZeux 1.xx and 2.xx files - except 1.xx MZB files which I haven't found out how to detect yet).

I've tried to make the functions relatively self-documenting, but I'm only one programmer and might have some idiosyncracies that I'm not aware of. If it seems useful but it's too hard to figure out how the detection works, let me know :-)

**Comment by Sembiance** [comment]
The attached [CAVERNS.MZX.ZIP](https://github.com/Sembiance/dexvert/files/9999192/CAVERNS.MZX.ZIP) MegaZeux world file has a non-zero byte at pos 25, but the `MZX` identifier is at pos 42 instead of 41 like the docs mention.

Do you have some other encrypted MegaZeux worlds that I could examine to see if it's always at 42 or if both 41 and 42 are possible offsets?

**Comment by asiekierka** [comment]
@kristomu pointed out that the specification might be inaccurate about the offset; for the time being, check pos 41 and 42.

**Comment by Sembiance** [comment]
MegaZeux files are identified now, back on Nov 14.
