### ISSUE TITLE
Wayback links should open in new tab/window

### ISSUE THREAD

**Issue by gingerbeardman** [Sembiance/dexvert#20]
I also think the reformatted links to Wayback Machine should open in a new tab/window and not in the DiscMaster frame. 

Currently it can feel like your viewing contents of the disc but you're viewing Wayback Machine inside the DiscMaster interface.

**Comment by Sembiance** [comment]
Good idea. The change has been made in the code so all future HTML pages will be this way.

An operation is underway to update all existing HTML pages, this will take... quite some time... to complete. Once finished I'll close this ticket :)

**Comment by Sembiance** [comment]
Done.

**Comment by gingerbeardman** [comment]
Thanks!
