### ISSUE TITLE
.BAS file detected by extension, but contents are unknown

### ISSUE THREAD

**Issue by jduerstock** [Sembiance/dexvert#22]
This RBBS-PC.BAS file (presumably from BASICA) is detected by extension, but is ultimately determined to be "unknown".

https://discmaster.textfiles.com/view/10618/The%20PC-Sig%20Library%20-%20Shareware%20for%20the%20IBM%20PC%20and%20Compatibles%20(PC-SIG)(Tenth%20Edition%20Disks%201-2804)(1991).iso/PC_SIGCD/01/5/DISK0152.ZIP/RBBS-PC.BAS

**Comment by gingerbeardman** [comment]
FWIW this is a binary file, not plain text.

[RBBS-PC.BAS.zip](https://github.com/Sembiance/dexvert/files/15213454/RBBS-PC.BAS.zip)

**Comment by jduerstock** [comment]
Errr, right, it's a tokenized GW-BASIC file, I believe.

**Comment by gingerbeardman** [comment]
perhaps useful
- http://justsolve.archiveteam.org/wiki/GW-BASIC_tokenized_file
- http://www.chebucto.ns.ca/~af380/GW-BASIC-tokens.html

**Comment by Sembiance** [comment]
dexvert now supports tokenized GW-BASIC files, including the protected versions.

This means discmaster2 will properly decode the linked RBBS-PC.BAS file and all other GW-BASIC files.

Thank you VERY much for the report and links :)
