### ISSUE TITLE
Support for other classic Macintosh text encodings

### ISSUE THREAD

**Issue by gingerbeardman** [Sembiance/dexvert#3]
Currently dexvert has support for MacRoman, which is assumed for all HFS format media. 

It would be great to get support for MacJapanese, and other classic Macintosh text encodings. 

[Personally](https://blog.gingerbeardman.com/2022/03/31/working-with-classic-macintosh-text-encodings-in-the-age-of-unicode/), I've used Tcl to convert classic Macintosh encodings to Unicode, as that support was written by Apple themselves. 

The tricky thing about this issue: there are no identifiers to signify which encoding a filename is using. It was assumed to be the same as the host OS. 

Much like dexvert assumes MacRoman, my own tool assumes MacJapanese (which is a superset of MacRoman so handles any included filenames that use MacRoman *fairly* well). It's a tricky issue for sure. 

**Maybe dexvert could use the encoding that matches the language set in the internet archive metadata?**

Example ISO: [https://archive.org/details/macpeople-1998-no-2](https://archive.org/details/macpeople-1998-no-2)

Please ask if any further information is required, I can most likely help. 

Thank you.

**Comment by gingerbeardman** [comment]
Sure thing! Of course there's no rush. There are a dozen or so regional Macintosh encodings.

It took me many months of dead ends to discover the Tcl shortcut. Glad I found it.

Whilst mainline Tcl doesn't have RiscOS or Atari ST encodings, you could generate your own and propose them. The encodings are very simple. That might make more sense if you were going to use Tcl for this purpose more widely. 

https://github.com/tcltk/tcl/tree/main/tools/encoding

**Comment by Sembiance** [comment]
Ok, dexvert now supports Japan encoded Mac CDs. Some work remains on the discmaster side before it can start injesting them but it shouldn't be too far away over there.

Closing this issue now that dexvert supports them.

Thanks again!

**Comment by gingerbeardman** [comment]
Arigato gozaimasu!
