### ISSUE TITLE
RSS for search results

### ISSUE THREAD

**Issue by gingerbeardman** [Sembiance/dexvert#6]
I thought it would be _very useful_ if search results could be returned as RSS.

This would let me check "automatically" (I'd set frequency to, say, once-per-day) for any matches of sought-after items/keywords in new DiscMaster uploads.

## just like archive.org

I subscribe to a few searches on Internet Archive to alert me to new matching uploads.

Example:
- https://archive.org/advancedsearch.php?q=%E8%8A%B1%E6%9C%AD&fl%5B%5D=identifier&sort%5B%5D=&sort%5B%5D=&sort%5B%5D=&rows=50&page=1&callback=callback&save=yes&output=rss
- this URL is created through [archive.org's Advanced Search page](https://archive.org/advancedsearch.php) 

I'd expect similar from DiscMaster:
- http://discmaster.textfiles.com/search?q=花札&fuzzy=fuzzy
- would (currently) return 3 items in the RSS feed

**Comment by Sembiance** [comment]
Good idea. A JSON output option would be useful too.

In the meantime, as of a few moments ago, you can now search for items `Added After` a specific date on DiscMaster.

**Comment by Sembiance** [comment]
You can now output search results as HTML, RSS or JSON.

**Comment by gingerbeardman** [comment]
Thanks!

It would be even better if the RSS was discoverable (by software and humans) from the html search results. 

ie. mentioned in the html head/meta.

**Comment by gingerbeardman** [comment]
Hmm. The following feed won't add to my RSS manager. 

http://discmaster.textfiles.com/search?q=hanafuda&fuzzy=fuzzy&outputAs=rss

![image](https://user-images.githubusercontent.com/49612/212496004-70b3049c-ba45-438a-bf74-22341d6e3f4d.png)

![image](https://user-images.githubusercontent.com/49612/212496009-30b90198-cbcd-479e-9021-25d16665b73d.png)

And I'm unable up validate the RSS using online validators. 

https://www.rssboard.org/rss-validator/check.cgi?url=http%3A%2F%2Fdiscmaster.textfiles.com%2Fsearch%3Fq%3Dhanafuda%26fuzzy%3Dfuzzy%26outputAs%3Drss

**Comment by Sembiance** [comment]
Looks like I got lots wrong with the RSS. I should have validated before, but it worked in Newsblur so I thought it was all set. I'll get the errors corrected. By the way, which RSS manager do you use so I can verify with it?

**Comment by Sembiance** [comment]
Figured out you were using FreshRSS. I've gotten it working in Fresh now, you should be all set.

Please try it again when you get the chance and let me know if you run into any issues.

**Comment by gingerbeardman** [comment]
All seems to be working. 

Any thoughts on:

> It would be even better if the RSS was discoverable (by software and humans) from the html search results.

**Comment by Sembiance** [comment]
> Any thoughts on:
> 
> > It would be even better if the RSS was discoverable (by software and humans) from the html search results.
> > ie. mentioned in the html head/meta.

That has also just been added.

**Comment by gingerbeardman** [comment]
Working great!

**Comment by gingerbeardman** [comment]
Results are coming in regularly 😀 

Feels good

**Comment by Sembiance** [comment]
> Results are coming in regularly grinning
> 
> Feels good

Oh good, very glad to hear it. Wasn't sure how it would work as new things were added, happy to hear it's working well :)
