### ISSUE TITLE
Directories are not showing up in search results

### ISSUE THREAD

**Issue by gingerbeardman** [Sembiance/dexvert#7]
## Search
- http://discmaster.textfiles.com/search?q=製品体験版
- http://discmaster.textfiles.com/search?q=ROLY_2

## Actual
- (no results)

## Expected
- http://discmaster.textfiles.com/browse/9412/MACPEOPLE-1998-NO2.ISO.7z/MACPEOPLE-1998-NO2.ISO/製品体験版
- http://discmaster.textfiles.com/browse/9412/MACPEOPLE-1998-NO2.ISO.7z/MACPEOPLE-1998-NO2.ISO/製品体験版/ROLY_2

**Comment by Sembiance** [comment]
Directory names are not currently indexed in the search database.

**Comment by gingerbeardman** [comment]
That would do it 😅

Happy New Year

**Comment by Sembiance** [comment]
The DiscMaster project is changing hands and I am no longer associated with it. I will be mantaining the dexvert project (the conversion part) including releasing a 1.0 beta release soon, but issues related directly to the DiscMaster website are no longer something I have control over and thus are out of my purview.

**Comment by Sembiance** [comment]
discmaster2 has full support for directories in the search results
![screenshot_2024-04-05_22:02:45](https://github.com/Sembiance/dexvert/assets/81436/3bb3f248-7603-4fef-9def-0261af5f7c57)
