### ISSUE TITLE
DiscMaster news dating

### ISSUE THREAD

**Issue by gingerbeardman** [Sembiance/dexvert#8]
May I humbly suggest that the date of publishing for the DiscMaster news blog entries is set to the end of the day, or the first minute of the following day. 

Currently, when they appear in my RSS they appear "in the past" some way down my timeline. 

Even though they're published "now" they're dated to the beginning of the day so appear many hours old.

**Comment by Sembiance** [comment]
Last night's RSS generation errored out. I'm looking into it :)

**Comment by Sembiance** [comment]
So, it generated, but generated as 23:59:59 Zulu time. Which I mean, is correct if the consumer is going off of Zulu time, but it's not when the RSS feed is actually generated which feels more like the goal. So I've updated it again to produce a Zulu timestamp that represents the time the cron job generates the RSS data, which is midnight.

We'll see how it goes tonight.

**Comment by gingerbeardman** [comment]
Coincidentally I am in Zulu timezone 😬

**Comment by Sembiance** [comment]
Cool, thanks for the update. I'll close this ticket, please re-open if tonight's update is weird and I'll revert back to 23:59:59 zulu.
